### ISSUE TITLE
Wont run?

### ISSUE THREAD

**Issue by barelylit** [AceExpert/ewelink-api-python#6]
Exception has occurred: TypeError
unsupported operand type(s) for |: 'types.GenericAlias' and 'type'
  File "C:\Utils\repository\ewelink-monitor\ewelink\models\enumerations.py", line 65, in Power
    def __getitem__(self, channels: tuple[int, ...] | int):
  File "C:\Utils\repository\ewelink-monitor\ewelink\models\enumerations.py", line 57, in <module>
    class Power(Enum):
    
    As soon as I try to run it ?

**Comment by aamiel1** [comment]
you need to run on Python 3.10+

**Comment by dantimofte** [comment]
try this example I wrote . it's basicaly a refactor without using the login decorator. Region is important so change it to match yours

https://github.com/dantimofte/ewelink-api-python/blob/master/main.py

```import asyncio
import ewelink


async def main():
    client: ewelink.Client = ewelink.Client("your_username", "email_or_phone", region="eu")
    await client.login()
    print(f"client version {client.region}")
    print(f"client user info: {client.user.info}")
    print(f"client devices {client.devices}")

    device = client.get_device('1000ce120a')

    print(f"device params {device.params}")
    # Raw device specific properties
    # can be accessed easily like: device.params.switch or device.params['startup'] (a subclass of dict)

    print(f"device state : {device.state}")
    print(f"device created_at: {device.created_at}")
    print("Brand Name: ", device.brand.name, "Logo URL: ", device.brand.logo.url)
    print("Device online? ", device.online)

    try:
        await device.on()
    except Exception as e:
        print("Device is offline!")
    await client.http.session.close()

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by agravet** [comment]
client: ewelink.Client = ewelink.Client("**your_username**", "email_or_phone", region="eu"), first parameter is actually the password. Otherwise works.

**Comment by activatedtmx** [comment]
For me there is some issue getting device type:

line 67, in __init__
    self.type: DeviceType = DeviceType.__dict__['_value2member_map_'].get(int(data.get('type', 0)), 0)
                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'a4'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024D793F8050>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000024D795FE040>, 23984.203)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x0000024D795FD630>, 23985.218)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000024D7962D910>

**Comment by Elio-Chedid** [comment]
import ewelink
from ewelink import Client, DeviceOffline, Power
import asyncio
import time

@ewelink.login('password', 'eamail')
async def main(client: Client):

        device = client.get_device('xxxxxx')
        print(device.params) 
        await device.edit(Power.on)

when I run this code I'm able to print the params but when it comes to device.edit an exception is thrown:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\ElioChedid\Desktop\tuya\sonoffff\ewelink-api-python\test.py", line 7, in <module>
    async def main(client: Client):
  File "c:\Users\ElioChedid\Desktop\tuya\sonoffff\ewelink-api-python\ewelink\client.py", line 94, in decorator
    result = asyncio.get_event_loop().run_until_complete(f(client))
  File "C:\Users\ElioChedid\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "c:\Users\ElioChedid\Desktop\tuya\sonoffff\ewelink-api-python\test.py", line 20, in main
    await device.edit(Power.on)
  File "c:\Users\ElioChedid\Desktop\tuya\sonoffff\ewelink-api-python\ewelink\models\device.py", line 86, in edit
    await self._state.ws.update_device_status(self.id, **params)
  File "c:\Users\ElioChedid\Desktop\tuya\sonoffff\ewelink-api-python\ewelink\ws.py", line 82, in update_device_status
    result = await asyncio.wait_for(fut, timeout = 10)
  File "C:\Users\ElioChedid\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

anybody knows how to fix it?
